config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :users, only: [:index, :show, :edit, :update] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 500 }

  after_create :post_comment_counter
  after_destroy :post_comment_counter

  def post_comment_counter
    post.update_column(:comments_counter, post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  belongs_to :post, foreign_key: :post_id

  after_create :post_like_counter
  after_destroy :post_like_counter

  def post_like_counter
    post.update_column(:likes_counter, post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_many :comments, foreign_key: :post_id, dependent: :destroy
  has_many :likes, foreign_key: :post_id, dependent: :destroy

  validates :title, presence: true, length: { maximum: 100 }
  validates :text, presence: true, length: { maximum: 1000 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_create :user_post_counter
  after_destroy :user_post_counter

  def user_post_counter
    user.update_column(:post_counter, user.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: :user_id
  has_many :posts, foreign_key: :user_id
  has_many :likes, foreign_key: :user_id

  validates :username, presence: true, uniqueness: true
  validates :post_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def recent_post_by_author(author_id)
    posts.where(author_id:).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name username photo bio country])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation, :username, :photo, :bio, :country)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).where(user_id: params[:user_id])
    @user = User.find_by(id: params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])

    return unless @user.nil?

    flash[:alert] = 'User not found'
    redirect_to users_path
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      flash[:notice] = 'User updated'
    else
      flash[:alert] = 'User not updated'
    end
    redirect_to edit_user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :bio, :photo, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogFull</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="w-11/12 flex flex-row-reverse justify-between mx-auto">
      <% if user_signed_in? %>
        <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class:"absolute z-10"  %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %>
        <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>
    </div>
    <div>
      <p class="left-3 relative max-w-56"><%= current_user&.username %></p>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<section>
  <h1>Posts by user</h1>

  <h2><%= @user&.username %></h2>

  <ul>
    <% @posts&.each do |post| %>
      <li>
        <h2><%= post.title %></h2>
        <p><%= post.text %></p>
      </li>
    <% end %>
  </ul>

  <%= link_to user_path(@user)  do %>
    <p>Back to user</p>
  <% end %>
</section>

app/views/users/edit.html.erb
<section>
  <%= form_with model: @user, method: :patch do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>

    <div>
      <%= form.label :bio %>
      <%= form.text_field :bio %>
    </div>

    <div>
      <%= form.label :photo %>
      <%= form.text_field :photo %>
    </div>

    <div>
      <%= form.label :country %>
      <%= form.text_field :country %>
    </div>

    <%= form.submit "Update" %>
  <% end %>


</section>

app/views/users/index.html.erb
<section>
  <% if current_user.present? %>
    <%= link_to "My profile", edit_user_path(current_user) %>
  <% end %>
  <ul class="text-center pt-20">
    <% @users&.each do |user| %>
      <li class="pb-20">

        <%= link_to user_path(user) do %>
          <h5 class="text-9xl"><%= user.username %></h5>
        <% end %>  
          <p><%= user.bio %></p>
        
      </li>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section>
  <h1>this is the show</h1>
  <h2><%= @user.name %></h2>
  <%= link_to users_path do %>
    <p>Back to index</p>
  <% end %>
  <%= link_to user_posts_path(@user) do %>
    <p>See all posts</p>
  <% end %>
</section>